<div class="number_select">
    <select class="" name="sort" id="change_number">
        <option value="{{ route('event_regist_search', [
            'number' => '10',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "10") selected @endif>10件</option>
        <option value="{{ route('event_regist_search',  [
            'number' => '30',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "30") selected @endif>30件</option>
        <option value="{{ route('event_regist_search',  [
            'number' => '50',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "50") selected @endif>50件</option>
        <option value="{{ route('event_regist_search',  [
            'number' => '100',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "100") selected @endif>100件</option>
        <option value="{{ route('event_regist_search',  [
            'number' => '300',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "300") selected @endif>300件</option>
        <option value="{{ route('event_regist_search',  [
            'number' => '500',
            'category_id' => $category_id,
            'event_name' => $event_name,
            'category_name' => $category_name,
            'meinichi_month' => $meinichi_month,
            'kaiki_before' => $kaiki_before,
            'kaiki_after' => $kaiki_after,
            'payment_before' => $payment_before,
            'payment_after' => $payment_after,
            'price_min' => $price_min,
            'price_max' => $price_max,
            'segaki_flg' => $segaki_flg,
            'star_flg' => $star_flg,
            'yakushiji_flg' => $yakushiji_flg,
            'kaiki_flg' => $kaiki_flg,
            'freeword' => $freeword,
            'item_categories' => $item_categories,
            'item_category_id' => $item_category_id,
            'hikuyousya_count' => $hikuyousya_count,
            'danka_count' => $danka_count,
            'category_id' => $category_id,
            'event_name' => $event_name,
            ]) }}"
        @if($number == "500") selected @endif>500件</option>
    </select>
</div>